site_name: Västanfors Poker Klubb

nav:
  - Hem: index.md
  - Player Of the Year:
    - POY 2024: poy_2024.md
    - Januari: 2024_01.md
    - Februari: 2024_02.md 
  - Om: about.md

theme:
  name: 'material'
  language: sv
  logo: assets/logo.png
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Byt till ljust läge

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Byt till mörkt läge

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Byt till systemets föredragna läge