site_name: Västanfors Poker Klubb

# nav:
#   - Hem: index.md
#   - Kommande Turneringar:
#     - kommande_turneringar/index.md
#     - kommande_turneringar/*
    # - TNL Klubbmästerskap 2024: kommande_turneringar/tnl_klubbmasterskap_2024.md
    # - VPK OPEN 2024: kommande_turneringar/vpkopen_2024.md
    # - PLO Klubbmästerskap 2024: kommande_turneringar/plo_klubbmasterskap_2024.md
    # - Novemberkåsan 2024: kommande_turneringar/novemberkasan_2024.md
    # - Årsfinal 2024: kommande_turneringar/arsfinal_2024.md
    # - VPK OPEN 2025: kommande_turneringar/vpkopen_2025.md
    # - TNL Klubbmästerskap 2025: kommande_turneringar/tnl_klubbmasterskap_2025.md
    # - PLO Klubbmästerskap 2025: kommande_turneringar/plo_klubbmasterskap_2025.md
    # - Novemberkåsan 2025: kommande_turneringar/novemberkasan_2025.md
    # - Årsfinal 2025: kommande_turneringar/arsfinal_2025.md

  # - Player Of the Year 2024:
  #   - poy/index.md
  #   # - POY 2024: poy_2024.md
  #   - Januari: poy/2024_01.md
  #   - Februari: poy/2024_02.md 
  # - Om: about.md

theme:
  name: 'material'
  language: sv
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Byt till ljust läge

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Byt till mörkt läge

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Byt till systemets föredragna läge


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

plugins:
  - awesome-pages
