site_name: Västanfors Poker Klubb
site_url: https://vastanforspoker.org/

theme:
  name: 'material'
  language: sv
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.path
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - toc.permalinks
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Byt till ljust läge

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Byt till mörkt läge

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Byt till systemets föredragna läge


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

plugins:
  - search
  - awesome-pages
  - social
  # - blog:
  #     blog_dir: .

extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/groups/vastanforspoker
      name: Vår privata grupp på Facebook

copyright: Copyright &copy; 2024 Västanfors Poker Klubb

#---------------------------------------------------------------------------------
